import { RequestHandler } from 'express'
import { validationResult } from 'express-validator'
import { ValidationError } from '../lib/errors'

/**
 * Check if any validation errors were generated by previous middleware.
 */
export const validationErrors: RequestHandler = (req, res, next) => {
  const errors = validationResult(req).array()

  if (errors.length > 0) {
    return next(new ValidationError(errors))
  }

  next()
}

export default validationErrors
